name: Wake Render Server

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: curl -X GET https://hyeju-portfolio.onrender.com
