name: Wake Render Server

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping Render server
        run: curl --silent --fail GET https://hyeju-portfolio.onrender.com || exit 1
